export const styles = {
  hoverScale: `hover:scale-110`,
  flex: `flex justify-center items-center`,
  mainLetter: `text-9xl font-mario text-orange`,
  nav_icons_media: `text-sm cursor-pointer hover:text-orange`,
  sidebar_icons: `text-xl active:text-orange cursor-pointer text-[28px]`,
  socials__Ul: `socials--gap flex py-[8px] items-center text-kulrang_text`,
  socials: `flex justify-center items-center rounded-full bg-black border-white border-2 w-9 h-9 hover:bg-orange`,
  form__btn: `border-2 border-orange text-orange rounded-md px-4 py-1 hover:bg-orange hover:text-white active:scale-95`,
  inputStyle: `peer placeholder-transparent h-10 w-full border-b-2 border-gray-300 text-gray-900 focus:outline-none focus:border-orange`,
  navbar_icons: `text-xl active:text-orange cursor-pointer p-3 hover:bg-orange hover:text-white rounded-[80%_60%_90%_60%_/_20%_80%_40%_90%] active:text-red-600`,
  portfolio_btn: `portfolio__btn inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white focus:outline-none active:scale-110 md:text-xs md:p-2`,
  form__square: `absolute inset-0 bg-gradient-to-r from-lightOrange to-orange shadow-lg transform -skew-y-6 hover:-skew-y-0 sm:skew-y-0 sm:-rotate-6 sm:rounded-3xl bg-red-300 hover:rotate-0`,
  imageStyles: `w-full h-full transition-[border-radius] duration-[1s] ease-[ease-out] animate-[morph_5s_ease-in-out_infinite_both_alternate] absolute overflow-hidden rounded-[60%_40%_30%_70%_/_60%_30%_70%_40%]`,
  form__input: `block px-2 pb-2 pt-2 w-full text-[16px] text-gray-900 bg-transparent rounded-lg border-2 border-gray-300 dark:text-orange dark:focus:border-orange-500 focus:outline-none focus:ring-0 focus:border-orange-600 peer`,
  pasStyle: `absolute left-0 -top-3.5 text-gray-600 text-sm peer-placeholder-shown:text-base peer-placeholder-shown:text-gray-440 peer-placeholder-shown:top-2 transition-all peer-focus:-top-3.5 peer-focus:text-gray-600 peer-focus:text-sm`,
  form__label: `absolute text-[16px] text-black duration-300 transform -translate-y-4 scale-75 top-2 z-10 origin-[0] bg-white px-2 peer-focus:px-2 peer-focus:text-orange-600 peer-focus:dark:text-orange-500 peer-placeholder-shown:scale-100 peer-placeholder-shown:-translate-y-1/2 peer-placeholder-shown:top-1/2 peer-focus:top-1 peer-focus:scale-75 peer-focus:-translate-y-4 left-1`,
};
